Repository vendi-ai/declarai, pull requests merged in 2023-09, with the labels that each got.

#118 Support jinja templates in docstrings
  README.md
  docs/features/jinja_templating.md
  src/declarai/chat.py
  src/declarai/operators/openai_operators/chat_operator.py
  src/declarai/operators/openai_operators/task_operator.py
  src/declarai/operators/operator.py
  src/declarai/operators/utils.py
  tests/api/test_chat_decorator.py
  tests/operators/test_utils.py
  tests/tasks/test_llm_chat.py
  tests/test_declarai.py
Labels: enhancement

#126 add colab intro notebook
  README.md
  examples/colab_intro.ipynb
Labels: documentation

#132 131 jinja is missing in project dependencies
  poetry.lock
  pyproject.toml
Labels: bug
