Repository vendi-ai/declarai, pull requests merged in 2023-08, with the labels that each got.

#81 update readme and docs urls
  README.md
  docs/overrides/main.html
Labels: documentation

#83 Update docs website
  docs/docs/CNAME
Labels: enhancement

#88 Fixed docs and added gpt-3.5-turbo-16k
  docs/docs/src/beginners-guide/debugging-tasks.md
  src/declarai/operators/__init__.py
Labels: documentation, enhancement

#97 fix : #96 Add support for both DECLARAI_OPEN_AI_KEY and OPENAI_API_KEY
  src/declarai/operators/openai_operators/settings.py
Labels: enhancement
